# Generated by Django 5.0 on 2023-12-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=250)),
                ('TIPO', models.CharField(max_length=250)),
                ('DESCRIPCION', models.CharField(max_length=250)),
                ('PRECIO', models.IntegerField()),
            ],
        ),
    ]
