# Generated by Django 5.0 on 2023-12-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=50)),
                ('APELLIDO', models.CharField(max_length=50)),
                ('USUARIO', models.CharField(max_length=50)),
                ('CORREO', models.CharField(max_length=50)),
                ('CLAVE', models.CharField(max_length=50)),
            ],
        ),
    ]
