# Generated by Django 5.2.5 on 2025-08-19 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_publisher_profile_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.author'),
        ),
    ]
