#XP per Mana Spent
xp_amount = 0.1
#% Max Mana per level
max_mana = 0.015
#% Mana Regen per level
mana_regen = 0.01
#Completely prevents PMMO Attacks for weapons that don't meet weapon requirements. Normally the attack registers but the damage doesn't, this will prevent on-hit effects happening.
pmmo_attack_handler = true

