
["Harder Farther Control Values"]
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 0
	#Limit Mob Farm XP and Drops (0 == no limit).  5 ticks (quarter second) is enough. 
	#Range: 0 ~ 120
	limitMobFarmsTimer = 5
	#Modify Max Hit Points (true) 
	makeMonstersHarderFarther = true
	#modifierMaxDistance: Distance til Maximum ModifierValue Applied
	#Range: 2000 ~ 100000
	modifierMaxDistance = 40000
	#modifierValue: Increase Mob Values by 1% to 999%
	#Range: 1 ~ 999
	modifierValue = 1
	#Worldspawn Safe Distance: No Mobs Will Spawn In this Range
	#Range: 64 ~ 160
	safeDistance = 64
	#minimumSafeAltitude: Mobs are 6% tougher below this altitude. 
	#Range: 1 ~ 48
	minimumSafeAltitude = 20
	#maximumSafeAltitude: Mobs are 9% tougher above this altitude.
	#Range: 76 ~ 160
	maximumSafeAltitude = 160
	#oddsDropExperienceBottle: Chance to drop 1 experience bottle.
	#Range: 0 ~ 100
	oddsDropExperienceBottle = 15
	#Common Loot Item: 
	itemCommon = "minecraft:emerald"
	#Uncommon Loot Item
	itemUncommon = "minecraft:diamond"
	#Rare Loot Item
	itemRare = "kubejs:gold_coin"
	#Modify Max Hit Points (true) 
	hpMaxMod = true
	#Modify Movement Speed (true) 
	speedMod = false
	#Modify Max Hit Points (true)
	atkDmgMod = false
	#Modify Knockback Resistance (true) 
	knockbackMod = false

