#Range: 1 ~ 4
itemsPerColumn = 4
#Range: 1 ~ 4
itemsPerRow = 4
diyData = false
showDevData = false
enchantsBlacklist = ["flimflam", "soulBound"]
hiddenTabs = ["dungeon", "enchantment", "mob", "villager", "worldgen", "plant"]
dimensionsBlacklist = [-11, 0, -1]
disableLootManagerReloading = false

