
[Settings]
	#Whether sneaking is required to display the tooltip.
	"Sneaking Required" = true
	#Whether to display a message telling the player to sneak.
	"Enable Sneaking Message" = true
	#If true, potions without descriptions will be listed in the logs.
	"Log Missing Descriptions" = false
	#Whether to display suspicious stew effects in the tooltip.
	"Suspicious Stew Tooltips" = false

