#If true the log messages will also be logged to the console and the log files. If false all messages will only be logged to the world-generation-profiler.log file
logInDefaultLog = true

#Chunk status threshold warn settings
[chunkStatusThreshold]
	#Range: 0 ~ 1000
	"minecraft:empty" = 50
	#Range: 0 ~ 1000
	"minecraft:structure_starts" = 50
	#Range: 0 ~ 1000
	"minecraft:structure_references" = 50
	#Range: 0 ~ 1000
	"minecraft:biomes" = 50
	#Range: 0 ~ 1000
	"minecraft:noise" = 50
	#Range: 0 ~ 1000
	"minecraft:surface" = 50
	#Range: 0 ~ 1000
	"minecraft:carvers" = 50
	#Range: 0 ~ 1000
	"minecraft:liquid_carvers" = 50
	#Range: 0 ~ 1000
	"minecraft:features" = 50
	#Range: 0 ~ 1000
	"minecraft:light" = 50
	#Range: 0 ~ 1000
	"minecraft:spawn" = 50
	#Range: 0 ~ 1000
	"minecraft:heightmaps" = 50
	#Range: 0 ~ 1000
	"minecraft:full" = 50

