# Generated by Django 4.2.7 on 2023-12-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=250)),
                ('descripcion_prod', models.CharField(max_length=250)),
                ('categoria', models.CharField(max_length=50)),
                ('cantidad_prod', models.IntegerField()),
                ('img1_prod', models.CharField(max_length=250)),
                ('img2_prod', models.CharField(max_length=250)),
                ('img3_prod', models.CharField(max_length=250)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
